Resources:
  apiHandlerServiceRoleF61AABDA:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: SSRApiStack/apiHandler/ServiceRole/Resource
  apiHandler8027B936:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Fn::Sub: cdk-hnb659fds-assets-${AWS::AccountId}-us-east-1
        S3Key: c952c7f7073788d6bbc6286596c225bade3fc61559ca2c6c20be59552553dee1.zip
      Role:
        Fn::GetAtt:
          - apiHandlerServiceRoleF61AABDA
          - Arn
      Environment:
        Variables:
          OPENAI_API_KEY:
            Fn::Join:
              - ""
              - - "{{resolve:secretsmanager:arn:aws:secretsmanager:us-east-1:"
                - Ref: AWS::AccountId
                - :secret:OpenAIApiKey:SecretString:::}}
      Handler: index.handler
      MemorySize: 128
      Runtime: nodejs18.x
      Timeout: 180
    DependsOn:
      - apiHandlerServiceRoleF61AABDA
    Metadata:
      aws:cdk:path: SSRApiStack/apiHandler/Resource
      aws:asset:path: asset.c952c7f7073788d6bbc6286596c225bade3fc61559ca2c6c20be59552553dee1
      aws:asset:is-bundled: false
      aws:asset:property: Code
  apiEndpoint154F0C18:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: apiEndpoint
    Metadata:
      aws:cdk:path: SSRApiStack/apiEndpoint/Resource
  apiEndpointDeploymentDCAB24BF5b6690d5e71e886f1620174da51e18e7:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId:
        Ref: apiEndpoint154F0C18
      Description: Automatically created by the RestApi construct
    DependsOn:
      - apiEndpointproxyANY17899448
      - apiEndpointproxyOPTIONS015491E4
      - apiEndpointproxy32486DF7
      - apiEndpointANY36EFCDEA
      - apiEndpointOPTIONS4ED99C11
    Metadata:
      aws:cdk:path: SSRApiStack/apiEndpoint/Deployment/Resource
  apiEndpointDeploymentStageprod8BE4C8B3:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId:
        Ref: apiEndpoint154F0C18
      DeploymentId:
        Ref: apiEndpointDeploymentDCAB24BF5b6690d5e71e886f1620174da51e18e7
      StageName: prod
    Metadata:
      aws:cdk:path: SSRApiStack/apiEndpoint/DeploymentStage.prod/Resource
  apiEndpointOPTIONS4ED99C11:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: OPTIONS
      ResourceId:
        Fn::GetAtt:
          - apiEndpoint154F0C18
          - RootResourceId
      RestApiId:
        Ref: apiEndpoint154F0C18
      AuthorizationType: NONE
      Integration:
        IntegrationResponses:
          - ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Amz-User-Agent'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
              method.response.header.Access-Control-Allow-Methods: "'OPTIONS,GET,PUT,POST,DELETE,PATCH,HEAD'"
            StatusCode: "204"
        RequestTemplates:
          application/json: "{ statusCode: 200 }"
        Type: MOCK
      MethodResponses:
        - ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Origin: true
            method.response.header.Access-Control-Allow-Methods: true
          StatusCode: "204"
    Metadata:
      aws:cdk:path: SSRApiStack/apiEndpoint/Default/OPTIONS/Resource
  apiEndpointproxy32486DF7:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Fn::GetAtt:
          - apiEndpoint154F0C18
          - RootResourceId
      PathPart: "{proxy+}"
      RestApiId:
        Ref: apiEndpoint154F0C18
    Metadata:
      aws:cdk:path: SSRApiStack/apiEndpoint/Default/{proxy+}/Resource
  apiEndpointproxyOPTIONS015491E4:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: OPTIONS
      ResourceId:
        Ref: apiEndpointproxy32486DF7
      RestApiId:
        Ref: apiEndpoint154F0C18
      AuthorizationType: NONE
      Integration:
        IntegrationResponses:
          - ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Amz-User-Agent'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
              method.response.header.Access-Control-Allow-Methods: "'OPTIONS,GET,PUT,POST,DELETE,PATCH,HEAD'"
            StatusCode: "204"
        RequestTemplates:
          application/json: "{ statusCode: 200 }"
        Type: MOCK
      MethodResponses:
        - ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Origin: true
            method.response.header.Access-Control-Allow-Methods: true
          StatusCode: "204"
    Metadata:
      aws:cdk:path: SSRApiStack/apiEndpoint/Default/{proxy+}/OPTIONS/Resource
  apiEndpointproxyANYApiPermissionSSRApiStackapiEndpointC6AA60F5ANYproxyD679FFC3:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - apiHandler8027B936
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:aws:execute-api:us-east-1:"
            - Ref: AWS::AccountId
            - ":"
            - Ref: apiEndpoint154F0C18
            - /
            - Ref: apiEndpointDeploymentStageprod8BE4C8B3
            - /*/*
    Metadata:
      aws:cdk:path: SSRApiStack/apiEndpoint/Default/{proxy+}/ANY/ApiPermission.SSRApiStackapiEndpointC6AA60F5.ANY..{proxy+}
  apiEndpointproxyANYApiPermissionTestSSRApiStackapiEndpointC6AA60F5ANYproxy69EAC6CF:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - apiHandler8027B936
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:aws:execute-api:us-east-1:"
            - Ref: AWS::AccountId
            - ":"
            - Ref: apiEndpoint154F0C18
            - /test-invoke-stage/*/*
    Metadata:
      aws:cdk:path: SSRApiStack/apiEndpoint/Default/{proxy+}/ANY/ApiPermission.Test.SSRApiStackapiEndpointC6AA60F5.ANY..{proxy+}
  apiEndpointproxyANY17899448:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: ANY
      ResourceId:
        Ref: apiEndpointproxy32486DF7
      RestApiId:
        Ref: apiEndpoint154F0C18
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - apiHandler8027B936
                  - Arn
              - /invocations
    Metadata:
      aws:cdk:path: SSRApiStack/apiEndpoint/Default/{proxy+}/ANY/Resource
  apiEndpointANYApiPermissionSSRApiStackapiEndpointC6AA60F5ANY442627F6:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - apiHandler8027B936
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:aws:execute-api:us-east-1:"
            - Ref: AWS::AccountId
            - ":"
            - Ref: apiEndpoint154F0C18
            - /
            - Ref: apiEndpointDeploymentStageprod8BE4C8B3
            - /*/
    Metadata:
      aws:cdk:path: SSRApiStack/apiEndpoint/Default/ANY/ApiPermission.SSRApiStackapiEndpointC6AA60F5.ANY..
  apiEndpointANYApiPermissionTestSSRApiStackapiEndpointC6AA60F5ANY74E44C79:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - apiHandler8027B936
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:aws:execute-api:us-east-1:"
            - Ref: AWS::AccountId
            - ":"
            - Ref: apiEndpoint154F0C18
            - /test-invoke-stage/*/
    Metadata:
      aws:cdk:path: SSRApiStack/apiEndpoint/Default/ANY/ApiPermission.Test.SSRApiStackapiEndpointC6AA60F5.ANY..
  apiEndpointANY36EFCDEA:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: ANY
      ResourceId:
        Fn::GetAtt:
          - apiEndpoint154F0C18
          - RootResourceId
      RestApiId:
        Ref: apiEndpoint154F0C18
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - apiHandler8027B936
                  - Arn
              - /invocations
    Metadata:
      aws:cdk:path: SSRApiStack/apiEndpoint/Default/ANY/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/1VPQU7DMBB8S+/O0pRLry2IUxFVeEDlJkvYJraj7JoSWfk7tlNQOc3MjjUz3sB2DeuVvnJRN13R0xnCu+i6UxWy82ONKnqn0GtzbjSEF29rIWfV04e950ccDTFHNSvSBkLlekxGwlnx40kzozDsEkQNe193KHvNsWGgVgte9QThkItiuewGygE3+oxD7yaDVtL1TsW5ba5ayO/unPyK8umaZN7YcXTf09/XlvjM51nlaSmEbJusNy+Dl3+PlHUNwoUfvsotlBsoVxcmKkZvhQxCteAPtux0tlUBAAA=
    Metadata:
      aws:cdk:path: SSRApiStack/CDKMetadata/Default
Outputs:
  apiEndpoint10A5FB54:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: apiEndpoint154F0C18
          - .execute-api.us-east-1.
          - Ref: AWS::URLSuffix
          - /
          - Ref: apiEndpointDeploymentStageprod8BE4C8B3
          - /
  apiurl:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: apiEndpoint154F0C18
          - .execute-api.us-east-1.
          - Ref: AWS::URLSuffix
          - /
          - Ref: apiEndpointDeploymentStageprod8BE4C8B3
          - /
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
Rules:
  CheckBootstrapVersion:
    Assertions:
      - Assert:
          Fn::Not:
            - Fn::Contains:
                - - "1"
                  - "2"
                  - "3"
                  - "4"
                  - "5"
                - Ref: BootstrapVersion
        AssertDescription: CDK bootstrap stack version 6 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI.